# Render deployment configuration for DNSWorth backend
# This file tells Render how to deploy the backend service

services:
  - type: web
    name: dnsworth-backend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      echo "Installing backend dependencies..."
      npm install
      echo "Backend dependencies installed successfully!"
    startCommand: |
      echo "Starting backend server..."
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
